version: '3.8'

services:
  web:
    # Берем Dockerfile из каталога
    build: ./lct_back
    # Запускаем тестовый сервер
    command: python manage.py runserver 0.0.0.0:8000
    # куда будут помещены данные из каталога
    volumes:
      - ./lct_back/:/usr/src/lct_back/
    # Открываем порт 8000 внутри и снаружи
    ports:
      - 8000:8000
      - 5672:5672
    # Файл содержащий переменные для контейнера
    env_file:
      - ./.env.dev