# Generated by Django 4.2.6 on 2023-11-08 18:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('stream_name', models.CharField(blank=True, max_length=128)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('url', models.CharField(max_length=512, unique=True)),
                ('username', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
