# Generated by Django 4.2.6 on 2023-11-09 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
