# Generated by Django 4.2.6 on 2023-11-09 21:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_stream_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('frame', models.ImageField(upload_to='media/')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
